name: NewBi
options:
  minimumXcodeGenVersion: 2.39.0
settings:
  base:
    SWIFT_VERSION: 5.10
packages:
  NewBiCore:
    path: .
targets:
  NewBi:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: NewBiApp
    info:
      path: NewBiApp/Info.plist
      properties:
        UIRequiresFullScreen: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ycx.newbi
        PRODUCT_NAME: NewBi
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
        INFOPLIST_KEY_UIRequiresFullScreen: YES
    dependencies:
      - package: NewBiCore
        product: NewBiCore
scheme:
  NewBi:
    build:
      targets:
        NewBi: all
    run:
      config: Debug
    archive:
      config: Release
